#!/usr/bin/env python3
"""Generate include/nasa_test_data.h from processed NASA C-MAPSS arrays."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = ROOT.parent
DEFAULT_X_TEST = PROJECT_ROOT / "datasets" / "NASA" / "processed" / "X_test.npy"
DEFAULT_Y_TEST = PROJECT_ROOT / "datasets" / "NASA" / "processed" / "Y_test.npy"
DEFAULT_PREDICTIONS = PROJECT_ROOT / "artifacts" / "nasa_kan" / "test_predictions.csv"
HEADER_PATH = ROOT / "include" / "nasa_test_data.h"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate include/nasa_test_data.h for the NASA inference binary."
    )
    parser.add_argument("--x-test", type=Path, default=DEFAULT_X_TEST)
    parser.add_argument("--y-test", type=Path, default=DEFAULT_Y_TEST)
    parser.add_argument("--predictions", type=Path, default=DEFAULT_PREDICTIONS)
    parser.add_argument("--output", type=Path, default=HEADER_PATH)
    parser.add_argument(
        "--max-samples",
        type=int,
        default=0,
        help="Limit generated samples. 0 means all available test samples.",
    )
    return parser.parse_args()


def c_float(value: float) -> str:
    text = f"{float(value):.9g}"
    if "e" not in text.lower() and "." not in text:
        text += ".0"
    return f"{text}f"


def format_1d_float_array(values: np.ndarray, indent: str) -> str:
    lines = []
    flat_values = values.reshape(-1)
    for index in range(0, len(flat_values), 4):
        chunk = flat_values[index : index + 4]
        lines.append(indent + ", ".join(c_float(value) for value in chunk))
    return ",\n".join(lines) if lines else indent + "0.0f"


def format_2d_float_array(values: np.ndarray, indent: str) -> str:
    rows = []
    inner_indent = indent + "    "
    for row in values:
        rows.append(
            indent + "{\n" + format_1d_float_array(row, inner_indent) + "\n" + indent + "}"
        )
    return ",\n".join(rows)


def summarize_windows(x: np.ndarray) -> np.ndarray:
    if x.ndim == 2:
        return x.astype(np.float32)
    if x.ndim != 3:
        raise ValueError(f"Unsupported X_test shape: {x.shape}")

    timesteps = np.arange(x.shape[1], dtype=np.float32)
    centered = timesteps - timesteps.mean()
    denominator = np.sum(centered**2)
    if denominator == 0.0:
        trend = np.zeros((x.shape[0], x.shape[2]), dtype=np.float32)
    else:
        trend = np.sum(x * centered.reshape(1, -1, 1), axis=1) / denominator

    return np.concatenate(
        [x.mean(axis=1), x.var(axis=1), trend],
        axis=1,
    ).astype(np.float32)


def load_reference_predictions(path: Path, count: int) -> np.ndarray | None:
    if not path.exists():
        return None

    values: list[float] = []
    with path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        if "predicted_rul" not in (reader.fieldnames or []):
            return None
        for row in reader:
            values.append(float(row["predicted_rul"]))

    if len(values) < count:
        raise ValueError(
            f"{path} has {len(values)} reference predictions, but {count} samples were requested."
        )
    return np.asarray(values[:count], dtype=np.float32)


def main() -> None:
    args = parse_args()
    x_test = np.load(args.x_test).astype(np.float32)
    y_test = np.load(args.y_test).astype(np.float32).reshape(-1)
    features = summarize_windows(x_test)

    if len(features) != len(y_test):
        raise ValueError(
            f"Feature/target length mismatch: {len(features)} features vs {len(y_test)} targets."
        )

    sample_count = len(features)
    if args.max_samples > 0:
        sample_count = min(sample_count, args.max_samples)
    features = features[:sample_count]
    y_test = y_test[:sample_count]
    reference_predictions = load_reference_predictions(args.predictions, sample_count)
    has_reference = reference_predictions is not None

    reference_block = ""
    if has_reference:
        reference_block = f"""
static const float NASA_TEST_REFERENCE_PREDICTIONS[NASA_TEST_SAMPLES] = {{
{format_1d_float_array(reference_predictions, "    ")}
}};
"""

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        f"""#ifndef NASA_TEST_DATA_H
#define NASA_TEST_DATA_H

/*
 * Auto-generated by scripts/nasa_test_to_header.py.
 * Source X: {args.x_test.resolve()}
 * Source y: {args.y_test.resolve()}
 * Do not edit this file by hand.
 */

#define NASA_TEST_SAMPLES {sample_count}
#define NASA_TEST_INPUT_DIM {features.shape[1]}
#define NASA_HAS_REFERENCE_PREDICTIONS {1 if has_reference else 0}

static const float NASA_TEST_FEATURES[NASA_TEST_SAMPLES][NASA_TEST_INPUT_DIM] = {{
{format_2d_float_array(features, "    ")}
}};

static const float NASA_TEST_TARGETS[NASA_TEST_SAMPLES] = {{
{format_1d_float_array(y_test, "    ")}
}};
{reference_block}
#endif /* NASA_TEST_DATA_H */
""",
        encoding="utf-8",
    )

    print(f"Generated {args.output}")
    print(f"samples = {sample_count}")
    print(f"input_dim = {features.shape[1]}")
    print(f"reference_predictions = {has_reference}")


if __name__ == "__main__":
    main()
